"
I have generated code.
"
Class {
	#name : #SWTranspiledCode,
	#superclass : #Object,
	#instVars : [
		'filename',
		'type',
		'code',
		'description'
	],
	#category : #'SWFortranByPharo-Client-Transpiler'
}

{ #category : #accessing }
SWTranspiledCode >> code [

	^ code
]

{ #category : #accessing }
SWTranspiledCode >> code: anObject [

	code := anObject
]

{ #category : #accessing }
SWTranspiledCode >> description [

	^ description
]

{ #category : #accessing }
SWTranspiledCode >> description: anObject [

	description := anObject
]

{ #category : #accessing }
SWTranspiledCode >> filename [

	^ filename
]

{ #category : #accessing }
SWTranspiledCode >> filename: anObject [

	filename := anObject
]

{ #category : #accessing }
SWTranspiledCode >> type [

	^ type
]

{ #category : #accessing }
SWTranspiledCode >> type: anObject [

	type := anObject
]
