"
I have an information about a wellknwon method.
"
Class {
	#name : #SWWellknownMethodInfo,
	#superclass : #Object,
	#instVars : [
		'return'
	],
	#category : #'SWFortranByPharo-Client-Analyzer'
}

{ #category : #api }
SWWellknownMethodInfo >> decode [
]

{ #category : #accessing }
SWWellknownMethodInfo >> pool: aObject [

]

{ #category : #accessing }
SWWellknownMethodInfo >> return [

	^ return
]

{ #category : #accessing }
SWWellknownMethodInfo >> return: anObject [

	return := anObject
]
